#if UNITY_EDITOR
using UnityEditor;
using UnityEngine;
using InternalRealtimeCSG;

namespace RealtimeCSG
{
	[CustomEditor(typeof(GeneratedMeshes))]
	[System.Reflection.Obfuscation(Exclude = true)]
	internal sealed class GeneratedMeshesEditor : Editor
	{
		public override void OnInspectorGUI()
		{
			var reference = this.target as GeneratedMeshes;
			if (reference == null)
				return;
			var destination = reference.owner;
			if (destination == null || !destination)
			{
				GUILayout.Space(10);
				GUILayout.Label("The owner of this mesh doesn't exist anymore!");
				GUILayout.Space(10);
			} else
			{
				GUILayout.Space(10);
				if (destination == InternalCSGModelManager.GetDefaultCSGModelForObject(reference))
				{
					GUILayout.Label("This mesh was automatically generated by the default CSG-model");
				} else
				{ 
					GUILayout.Label("This mesh was automatically generated by a CSG-model called '" + destination.name + "'");
					GUILayout.Space(10);
					if (GUILayout.Button("Take me there"))
					{
						Selection.activeObject = destination;
					}
				}
				GUILayout.Space(10);
			}
		}
	}
}
#endif